name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main   # Trigger deploy when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH key for accessing remote server
      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      # Step 3: Add server to known hosts (for security)
      - name: Add SSH known hosts
        run: ssh-keyscan -H your-server-ip >> ~/.ssh/known_hosts

      # Step 4: Copy application code to the server
      - name: Copy files to remote server
        run: |
          scp -r ./ username@your-server-ip:/path/to/remote/app/

      # Step 5: SSH into the server and run Docker Compose commands
      - name: Deploy with Docker Compose
        run: |
          ssh username@your-server-ip << 'EOF'
            cd /path/to/remote/app/
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
