name: Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - main   # Trigger deploy when code is pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use Ubuntu runner

    steps:
      # Step 1: Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Set up SSH key for accessing remote server
      - name: Set up SSH
        run: |
          mkdir -p ~/.ssh
          touch ~/.ssh/id_rsa
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          eval $(ssh-agent -s)
          ssh-add ~/.ssh/id_rsa

      # Step 3: Add server to known hosts (for security)
      - name: Add SSH known hosts
        run: ssh-keyscan -H 51.250.107.205 >> ~/.ssh/known_hosts
      #Step 3.5 List of files
      - name: List files in the current directory
        run: ls -alh

      # Step 4: Copy application code to the server
      - name: Copy files to remote server
        run: |
          scp -r ./* admin@51.250.107.205:/home/admin/app

      # Step 5: SSH into the server and run Docker Compose commands
      - name: Deploy with Docker Compose
        run: |
          ssh admin@51.250.107.205 << 'EOF'
            cd /home/admin/app
            sudo docker-compose down
            sudo docker-compose up -d --build
          EOF
